/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package runner;

import java.util.List;
import managefile.DeliveryReview;
import managefile.readFile;

/**
 *
 * @author Asus
 */
public class RunnerReviewPanel extends javax.swing.JPanel {
    runnerAccountManager acc = new runnerAccountManager();
    private String reviewDeliveryId;
    DeliveryReview deliveryReview = new DeliveryReview();
    readFile read = new readFile();
    private String rating;
    private String comment;
    private String datetime;
    /**
     * Creates new form runnerReviewPanel
     */
    public RunnerReviewPanel(String deliveryReviewId) {
        initComponents();
        this.reviewDeliveryId = deliveryReviewId;
        List<DeliveryReview> reviews = read.readDeliveryReview(deliveryReview.getFilepath());
        for(DeliveryReview review : reviews){
            if(review.getReviewID().equals(deliveryReviewId)){
                this.rating = review.getRating();
                this.datetime = review.getDatetime();
                this.comment = review.getComments();
                
            }
        }
        reviewIdLabel.setText("ReviewId " + "#" + deliveryReviewId);
        ratingLabel.setText(rating);
        datetimeLabel.setText(datetime);
        commentTextField.setText(comment);
        ratingImage.setIcon(acc.scale.processImage("src\\main\\java\\image_repository\\star.png", 30, 30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new method.RoundedPanel();
        reviewIdLabel = new javax.swing.JLabel();
        datetimeLabel = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentTextField = new javax.swing.JTextArea();
        ratingImage = new javax.swing.JLabel();

        reviewIdLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        reviewIdLabel.setText("ReviewId #RD123");

        datetimeLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        datetimeLabel.setText("DateTime");

        ratingLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        ratingLabel.setText("Ratings");

        commentTextField.setColumns(20);
        commentTextField.setRows(5);
        commentTextField.setFocusable(false);
        jScrollPane1.setViewportView(commentTextField);

        ratingImage.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addComponent(reviewIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datetimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ratingImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reviewIdLabel)
                    .addComponent(datetimeLabel)
                    .addComponent(ratingLabel)
                    .addComponent(ratingImage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commentTextField;
    private javax.swing.JLabel datetimeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ratingImage;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JLabel reviewIdLabel;
    private method.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
