/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package runner;

import java.util.List;
import managefile.DeliveryReview;
import managefile.readFile;

/**
 *
 * @author Asus
 */
public class RunnerReviewPanel extends javax.swing.JPanel {
    private String reviewDeliveryId;
    DeliveryReview deliveryReview = new DeliveryReview();
    readFile read = new readFile();
    private String rating;
    private String comment;
    private String datetime;
    /**
     * Creates new form runnerReviewPanel
     */
    public RunnerReviewPanel(String deliveryReviewId) {
        initComponents();
        this.reviewDeliveryId = deliveryReviewId;
        List<DeliveryReview> reviews = read.readDeliveryReview(deliveryReview.getFilepath());
        for(DeliveryReview review : reviews){
            if(review.getReviewID().equals(deliveryReviewId)){
                this.rating = review.getRating();
                this.datetime = review.getDatetime();
                this.comment = review.getComments();
                
            }
        }
        reviewIdLabel.setText("ReviewId " + "#" + deliveryReviewId);
        ratingLabel.setText("*" + rating);
        datetimeLabel.setText(datetime);
        commentTextField.setText(comment);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reviewIdLabel = new javax.swing.JLabel();
        datetimeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentTextField = new javax.swing.JTextArea();
        ratingLabel = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        reviewIdLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        reviewIdLabel.setText("ReviewId #RD123");

        datetimeLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        datetimeLabel.setText("DateTime");

        commentTextField.setColumns(20);
        commentTextField.setRows(5);
        commentTextField.setFocusable(false);
        jScrollPane1.setViewportView(commentTextField);

        ratingLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        ratingLabel.setText("Ratings");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reviewIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(datetimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ratingLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reviewIdLabel)
                    .addComponent(datetimeLabel)
                    .addComponent(ratingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commentTextField;
    private javax.swing.JLabel datetimeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JLabel reviewIdLabel;
    // End of variables declaration//GEN-END:variables
}
