/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package runner;

import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import managefile.Data;
import managefile.Delivery;
import managefile.Food;
import managefile.Order;
import managefile.OrderItems;
import managefile.Runner;
import managefile.readFile;

/**
 *
 * @author Asus
 */
public class RunnerTaskPanel extends javax.swing.JPanel {
    Delivery delivery = new Delivery();
    Order order = new Order();
    readFile read = new readFile();
    OrderItems orderitems = new OrderItems();
    Food food = new Food();
    Data data = new Data();
    Runner runner = new Runner();
    private String deliveryId;
    private String totalAmount;
    private String description;
    private String address;
    private String date;
    private String time;
    private String orderId;
    private String runnerId;
    private RunnerTask parent;
    /**
     * Creates new form RunnerTaskPanel
     */
    public RunnerTaskPanel(String deliveryId, RunnerTask parent) {
        initComponents();
        this.parent = parent;
        this.deliveryId = deliveryId;
        List<Delivery> deliveries = read.readDelivery(delivery.getFilepath());
        for(Delivery delivery : deliveries){
            if(delivery.getDeliveryID().equals(deliveryId)){
                this.deliveryId = delivery.getDeliveryID();
                this.runnerId = delivery.getRunnerID();
                this.description = delivery.getDescription();
                this.date = delivery.getDatetime().split("T")[0];
                this.time = delivery.getDatetime().split("T")[1];
                this.totalAmount = String.valueOf(delivery.getDeliveryFees());
                
            }
        }
        deliveryIdLabel.setText("Delivery #" + deliveryId);
        dateLabel.setText(date);
        timeLabel.setText(time);
        totalAmountLabel.setText(totalAmount);
        
        //get order items
        List<Order> orders = read.readOrder(order.getFilepath());
        for (Order order : orders){
            if(order.getDeliveryID().equals(deliveryId)){
                this.orderId = order.getOrderID();
                this.address = order.getOrderTypeDetails();
            }
        }
        addressLabel.setText(address);
        List<OrderItems> orderItems = read.readOrderItems(orderitems.getFilepath());
        List<Food> foods = read.readFood(food.getFilepath());
        List<String[]> foodsOrdered = new ArrayList(); 
        for(OrderItems orderItem : orderItems){
            if(orderItem.getOrderID().equals(orderId)){
                String[] foodOrder = new String[2];
                String foodId = orderItem.getFoodID();
                for (Food food : foods){
                    if(food.getId().equals(foodId)){
                        foodOrder[0] = food.getName();
                    }
                }
                foodOrder[1] = orderItem.getQuantity();
                foodsOrdered.add(foodOrder);
            }
        }
        
        for (String[] foodOrder : foodsOrdered) {
            System.out.println(foodOrder);
            String foodName = foodOrder[0];
            String quantity = foodOrder[1];
            System.out.println(foodName);
            String text = "• " + foodName + " x " + quantity;

            // Create a label for each food item
            JLabel foodLabel = new JLabel(text);
            foodLabel.setFont(new Font("Arial", Font.PLAIN, 16));  // Customize the font if needed

            // Ensure the panel uses BoxLayout for vertical stacking
            itemListPanel.setLayout(new BoxLayout(itemListPanel, BoxLayout.Y_AXIS));

            // Add the label to the panel
            itemListPanel.add(foodLabel);

            // Optionally, you can add some space between items
            itemListPanel.add(Box.createVerticalStrut(5));  // Adds space between the labels

            // Make the frame visible
            this.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new method.RoundedPanel();
        deliveryIdLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        itemListPanel = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        completeBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();

        deliveryIdLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        deliveryIdLabel.setText("Delivery #D14");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Delivery Address: ");

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLabel.setText("Address");
        addressLabel.setAutoscrolls(true);
        addressLabel.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Description:");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(descriptionTextArea);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Order Items: ");

        itemListPanel.setLayout(new java.awt.BorderLayout());

        timeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeLabel.setText("Time");

        completeBtn.setText("Completed");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Total Amount:");

        totalAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalAmountLabel.setText("RMXXX");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        dateLabel.setText("Date");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(deliveryIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addComponent(itemListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(completeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryIdLabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(itemListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(completeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        // TODO add your handling code here:
        data.updateData(deliveryId,7,"Sent",delivery.getFilepath());
        data.updateData(orderId,9,"Sent",order.getFilepath());
        data.updateData(runnerId,5,"Available",runner.getFilepath());
        parent.removeTaskPanel(this);
        JOptionPane.showMessageDialog(
            null, 
            "Order completed successfully!", 
            "Order Complete", 
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_completeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton completeBtn;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel deliveryIdLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JPanel itemListPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private method.RoundedPanel roundedPanel1;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel totalAmountLabel;
    // End of variables declaration//GEN-END:variables
}
