/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import customer.login;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import method.scaleImage;

/**
 *
 * @author TPY
 */
public class MainMenu extends javax.swing.JFrame {

    scaleImage scaleImage = new scaleImage();
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.setTitle("Main Menu");
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null); 
        logoLabel.setIcon(scaleImage.processImage("src\\main\\java\\image_repository\\gastrogo.png", 250, 192));
                
        leftPanel.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;  
        gbc.gridy = 0;  
        gbc.anchor = GridBagConstraints.CENTER; 
        gbc.fill = GridBagConstraints.NONE; 

        leftPanel.add(logoLabel, gbc);
    }
        
    public void run() {
        new MainMenu().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgBackground = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        managerButton = new method.roundedButton();
        runnerButton = new method.roundedButton();
        customerButton = new method.roundedButton();
        adminButton = new method.roundedButton();
        vendorButton = new method.roundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 565));

        bgBackground.setLayout(new java.awt.BorderLayout());

        leftPanel.setBackground(new java.awt.Color(39, 40, 56));
        leftPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leftPanel.setMinimumSize(new java.awt.Dimension(500, 568));
        leftPanel.setPreferredSize(new java.awt.Dimension(500, 568));

        logoLabel.setAlignmentX(0.5F);
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bgBackground.add(leftPanel, java.awt.BorderLayout.WEST);

        rightPanel.setBackground(new java.awt.Color(126, 127, 154));
        rightPanel.setMaximumSize(new java.awt.Dimension(32767, 32767));
        rightPanel.setMinimumSize(new java.awt.Dimension(500, 568));
        rightPanel.setPreferredSize(new java.awt.Dimension(500, 568));
        rightPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 222, 138));
        jLabel1.setText("LOGIN AS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(116, 196, 0, 0);
        rightPanel.add(jLabel1, gridBagConstraints);

        managerButton.setForeground(new java.awt.Color(60, 63, 65));
        managerButton.setText("MANAGER");
        managerButton.setBorderColor(new java.awt.Color(126, 127, 154));
        managerButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        managerButton.setRadius(30);
        managerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 99;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 0, 143);
        rightPanel.add(managerButton, gridBagConstraints);

        runnerButton.setForeground(new java.awt.Color(60, 63, 65));
        runnerButton.setText("RUNNER");
        runnerButton.setBorderColor(new java.awt.Color(126, 127, 154));
        runnerButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        runnerButton.setRadius(30);
        runnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runnerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 137, 143);
        rightPanel.add(runnerButton, gridBagConstraints);

        customerButton.setForeground(new java.awt.Color(60, 63, 65));
        customerButton.setText("CUSTOMER");
        customerButton.setBorderColor(new java.awt.Color(126, 127, 154));
        customerButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        customerButton.setRadius(30);
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 0, 143);
        rightPanel.add(customerButton, gridBagConstraints);

        adminButton.setForeground(new java.awt.Color(60, 63, 65));
        adminButton.setText("ADMIN");
        adminButton.setBorderColor(new java.awt.Color(126, 127, 154));
        adminButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        adminButton.setRadius(30);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 0, 143);
        rightPanel.add(adminButton, gridBagConstraints);

        vendorButton.setForeground(new java.awt.Color(60, 63, 65));
        vendorButton.setText("VENDOR");
        vendorButton.setBorderColor(new java.awt.Color(126, 127, 154));
        vendorButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        vendorButton.setRadius(30);
        vendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 151, 0, 143);
        rightPanel.add(vendorButton, gridBagConstraints);

        bgBackground.add(rightPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bgBackground.getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runnerButtonActionPerformed
        this.dispose();
        UserLogin userlogin = new UserLogin("runner");
        userlogin.run();
    }//GEN-LAST:event_runnerButtonActionPerformed

    private void vendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorButtonActionPerformed
        this.dispose();
        UserLogin userlogin = new UserLogin("vendor");
        userlogin.run();
    }//GEN-LAST:event_vendorButtonActionPerformed

    private void managerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButtonActionPerformed
        this.dispose();
        UserLogin userlogin = new UserLogin("manager");
        userlogin.run();
    }//GEN-LAST:event_managerButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        this.dispose();
        UserLogin userlogin = new UserLogin("admin");
        userlogin.run();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        this.dispose();
        login login = new login();
        login.run();
    }//GEN-LAST:event_customerButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private method.roundedButton adminButton;
    private javax.swing.JPanel bgBackground;
    private method.roundedButton customerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logoLabel;
    private method.roundedButton managerButton;
    private javax.swing.JPanel rightPanel;
    private method.roundedButton runnerButton;
    private method.roundedButton vendorButton;
    // End of variables declaration//GEN-END:variables
}
