/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import vendor.*;

/**
 *
 * @author TPY
 */
public class RunnerList extends javax.swing.JPanel {

    /**
     * Creates new form VendorStore
     */
    public RunnerList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RunnerLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(126, 127, 154));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        RunnerLabel.setBackground(new java.awt.Color(255, 255, 51));
        RunnerLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        RunnerLabel.setForeground(new java.awt.Color(255, 255, 51));
        RunnerLabel.setText("Runner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(RunnerLabel)
                .addContainerGap(797, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(RunnerLabel)
                .addContainerGap(706, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RunnerLabel;
    // End of variables declaration//GEN-END:variables
}
