/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.awt.Dimension;
import java.util.List;
import managefile.Feedback;

/**
 *
 * @author Asus
 */
public class FeedbackPanel extends javax.swing.JPanel {
    private String feedbackId;
    private String managerId;
    private String feedbackDescription;
    private String feedbackDatetime;
    Feedback feedback = new Feedback();
    managerAccountManager acc = new managerAccountManager();
    private ManagerComplaints parent;
    /**
     * Creates new form FeedbackPanel
     */
    public FeedbackPanel(String feedbackId, String managerId, ManagerComplaints parent) {
        this.feedbackId = feedbackId;
        this.managerId = managerId;
        this.setSize(900, 100);
        this.setPreferredSize(new Dimension(900, 100));
        this.setMaximumSize(new Dimension(900, 100));
        this.parent = parent;
        initComponents();
        Feedback feedbackDetails = acc.getFeedbackDetails(feedbackId);
        feedbackIdLabel.setText(feedbackDetails.getFeedbackID());
        feedbackDescriptionLabel.setText(feedbackDetails.getDescription());
        datetimeLabel.setText(feedbackDetails.getDatetime());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        approveBtn = new method.RoundedButton();
        feedbackIdLabel = new javax.swing.JLabel();
        feedbackDescriptionLabel = new javax.swing.JLabel();
        datetimeLabel = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        approveBtn.setText("Approve");
        approveBtn.setRadius(150);
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        feedbackIdLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        feedbackIdLabel.setText("feedbackID");

        feedbackDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        feedbackDescriptionLabel.setText("Description");

        datetimeLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        datetimeLabel.setText("2024-11-12T112:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(feedbackIdLabel)
                .addGap(31, 31, 31)
                .addComponent(feedbackDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datetimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feedbackIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feedbackDescriptionLabel)
                    .addComponent(datetimeLabel))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        acc.approveFeedback(feedbackId, managerId);
        parent.removeFeedbackPanel(this);
    }//GEN-LAST:event_approveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private method.RoundedButton approveBtn;
    private javax.swing.JLabel datetimeLabel;
    private javax.swing.JLabel feedbackDescriptionLabel;
    private javax.swing.JLabel feedbackIdLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
