/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import managefile.Feedback;

/**
 *
 * @author Asus
 */
public class FeedbackPanel extends javax.swing.JPanel {
    private String feedbackId;
    private String managerId;
    private String feedbackDescription;
    private String feedbackDatetime;
    Feedback feedback = new Feedback();
    managerAccountManager acc = new managerAccountManager();
    private ManagerComplaints parent;
    /**
     * Creates new form FeedbackPanel
     */
    public FeedbackPanel(String feedbackId, String managerId, ManagerComplaints parent) {
        this.feedbackId = feedbackId;
        this.managerId = managerId;
        this.setSize(950, 180);
        this.setPreferredSize(new Dimension(950, 180));
        this.setMaximumSize(new Dimension(950, 180));
        this.parent = parent;
        initComponents();
        Feedback feedbackDetails = acc.getFeedbackDetails(feedbackId);
        feedbackIdLabel.setText(feedbackDetails.getFeedbackID());
        feedbackDescriptionLabel.setText(feedbackDetails.getDescription());
        datetimeLabel.setText(feedbackDetails.getDatetime());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new method.RoundedPanel();
        feedbackIdLabel = new javax.swing.JLabel();
        feedbackDescriptionLabel = new javax.swing.JLabel();
        datetimeLabel = new javax.swing.JLabel();
        approveBtn = new method.RoundedButton();

        feedbackIdLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        feedbackIdLabel.setText("feedbackID");

        feedbackDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        feedbackDescriptionLabel.setText("Description");

        datetimeLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        datetimeLabel.setText("2024-11-12T112:00");

        approveBtn.setText("Complete");
        approveBtn.setRadius(150);
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(feedbackIdLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feedbackDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datetimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                        .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(feedbackIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedbackDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datetimeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        acc.approveFeedback(feedbackId, managerId);
        parent.removeFeedbackPanel(this);
        JOptionPane.showMessageDialog(
            null, 
            "Feedback Updated Successfully!", 
            "Feedback Updated", 
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_approveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private method.RoundedButton approveBtn;
    private javax.swing.JLabel datetimeLabel;
    private javax.swing.JLabel feedbackDescriptionLabel;
    private javax.swing.JLabel feedbackIdLabel;
    private method.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
