/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.Arrays;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import managefile.Vendor;
import managefile.Data;

/**
 *
 * @author Asus
 */
public class managerRevenue extends javax.swing.JPanel { 
    Vendor vendor = new Vendor();
    Data data = new Data();
    String vendorFilepath = vendor.getFilepath();
    /**
     * Creates new form managerRevenue
     */
    public managerRevenue() {
        initComponents();
        this.setSize(1000,300);
        this.setLayout(new BorderLayout());
        JPanel containerPanel = new JPanel(new GridLayout(0, 3, 10, 10));
        
        List<String[]> vendors = data.readRolesFromFile(vendorFilepath);
        System.out.println(vendors);
        for (String[] vendor : vendors){
            String vendorId = vendor[0];
            String vendorName = vendor[1];
            String vendorStallName = vendor[5];
            String vendorStallType = vendor[6];
            String vendorImagePath = vendor[7];
            vendorPanel panel = new vendorPanel("Revenue", vendorId, vendorName, vendorStallName, vendorStallType, vendorImagePath);
            containerPanel.add(panel);
        }
        JScrollPane scrollPane = new JScrollPane(containerPanel);
        scrollPane.setPreferredSize(new Dimension(628,460));
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.getVerticalScrollBar().setUnitIncrement(20);
        scrollPane.getHorizontalScrollBar().setUnitIncrement(20);
        scrollPane.setBorder(null);
        this.add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1000, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
