/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manager;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;
import managefile.Data;
import managefile.Manager;
import manager.ManagerHome;
/**
 *
 * @author Asus
 */
public class managerMain extends javax.swing.JFrame {
    private String managerId;
    Manager manager = new Manager();
    Data data = new Data();
    /**
     * Creates new form managerMain
     */
    public managerMain(String managerId) {
        initComponents();
        String managerName;
        this.managerId = managerId;
        contentPanel.setOpaque(false);
        this.setSize(1060, 600);
        
        managerName = data.retrieveData(managerId, 1, manager.getFilepath());
        jLabel2.setText("Manager " + managerName);
        
        LocalDateTime now = LocalDateTime.now();
        // Format the date and time as desired
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        String formattedDateTime = now.format(formatter);
        jLabel3.setText(formattedDateTime);
       
        ManagerHome home = new ManagerHome(managerId);
        switchToPanel(home);
    }
    
    private void switchToPanel(JPanel panel) {
        panel.setSize(contentPanel.getWidth(), contentPanel.getHeight());
        panel.setLocation(0, 0);
        contentPanel.removeAll();
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }
    
    public void actionPerformed(ActionEvent e){
        if( e.getSource() == revenueBtn){
            managerRevenue managerRevenue = new managerRevenue();
            switchToPanel(managerRevenue);
        }else if( e.getSource() == deliveryBtn){
            managerDelivery managerDelivery = new managerDelivery();
            switchToPanel(managerDelivery);
        }else if(e.getSource() == complaintsBtn){
            ManagerComplaints managerComplaints = new ManagerComplaints(managerId);
            switchToPanel(managerComplaints);
        }else if(e.getSource() == vendorBtn){
            ManagerVendor managerVendor = new ManagerVendor();
            switchToPanel(managerVendor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        revenueBtn = new javax.swing.JButton();
        deliveryBtn = new javax.swing.JButton();
        complaintsBtn = new javax.swing.JButton();
        vendorBtn = new javax.swing.JButton();
        welcomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1060, 500));

        jPanel4.setBackground(new java.awt.Color(235, 148, 134));
        jPanel4.setLayout(new java.awt.GridLayout());

        revenueBtn.setText("Revenue");
        revenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueBtnActionPerformed(evt);
            }
        });
        jPanel4.add(revenueBtn);

        deliveryBtn.setText("Delivery");
        deliveryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryBtnActionPerformed(evt);
            }
        });
        jPanel4.add(deliveryBtn);

        complaintsBtn.setText("Complaints");
        complaintsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintsBtnActionPerformed(evt);
            }
        });
        jPanel4.add(complaintsBtn);

        vendorBtn.setText("Vendor");
        vendorBtn.setPreferredSize(new java.awt.Dimension(75, 50));
        vendorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorBtnActionPerformed(evt);
            }
        });
        jPanel4.add(vendorBtn);

        welcomePanel.setBackground(new java.awt.Color(39, 40, 56));
        welcomePanel.setPreferredSize(new java.awt.Dimension(1000, 100));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Welcome back,");
        welcomePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 6, -1, 41));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Manager <<Name>>");
        welcomePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 59, 434, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("<<DATETIME>>");
        welcomePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 28, -1, 50));

        contentPanel.setPreferredSize(new java.awt.Dimension(1000, 300));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deliveryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryBtnActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_deliveryBtnActionPerformed

    private void complaintsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintsBtnActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_complaintsBtnActionPerformed

    private void vendorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorBtnActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_vendorBtnActionPerformed

    private void revenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueBtnActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt); 
    }//GEN-LAST:event_revenueBtnActionPerformed

    /**
     * @param args the command line arguments
     */
 
    public void run() {
        new managerMain(managerId).setVisible(true);
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton complaintsBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deliveryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton revenueBtn;
    private javax.swing.JButton vendorBtn;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables

}
