/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import managefile.Data;
import managefile.Runner;

/**
 *
 * @author Asus
 */
public class managerDelivery extends javax.swing.JPanel {
    Runner runner = new Runner();
    Data data = new Data();
    String runnerFilepath = runner.getFilepath();
    
    /**
     * Creates new form managerDelivery
     */
    public managerDelivery() {
        initComponents();
        this.setSize(1000,300);
        this.setLayout(new BorderLayout());
        JPanel containerPanel = new JPanel(new GridLayout(0, 3, 5, 5));
        
        List <String[]> runners = data.readRolesFromFile(runnerFilepath);
        System.out.println(runners);
        for (String[] runner : runners ){
            String runnerId = runner[0];
            String runnerName = runner[1];
            String runnerEmail = runner[2];
            String runnerPhone = runner[3];
            runnerPanel panel = new runnerPanel(runnerId, runnerName, runnerEmail, runnerPhone);
            containerPanel.add(panel);
        }
        JScrollPane scrollPane = new JScrollPane(containerPanel);
        scrollPane.setPreferredSize(new Dimension(628,480));
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.getVerticalScrollBar().setUnitIncrement(20);
        scrollPane.getHorizontalScrollBar().setUnitIncrement(20);
        scrollPane.setBorder(null);
        this.add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
