/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.awt.Dimension;

/**
 *
 * @author Asus
 */
public class ratingPanel extends javax.swing.JPanel {
    managerAccountManager acc = new managerAccountManager();
    /**
     * Creates new form ratingPanel
     */
    public ratingPanel(String[] reviews) {
        initComponents();
        this.setPreferredSize(new Dimension(400, 110));
        this.setMaximumSize(new Dimension(500,110));
        reviewIdLabel.setText(reviews[0]);
        reviewCommentLabel.setText(reviews[4]);
        ratingsLabel.setText(reviews[3]);
        ratingImage.setIcon(acc.scale.processImage("src\\main\\java\\image_repository\\star.png", 44, 43));
        datatimeLabel.setText(reviews[5]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new method.RoundedPanel();
        reviewIdLabel = new javax.swing.JLabel();
        reviewCommentLabel = new javax.swing.JLabel();
        datatimeLabel = new javax.swing.JLabel();
        ratingsLabel = new javax.swing.JLabel();
        ratingImage = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(380, 110));

        roundedPanel1.setMaximumSize(new java.awt.Dimension(530, 98));
        roundedPanel1.setMinimumSize(new java.awt.Dimension(530, 98));
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reviewIdLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        reviewIdLabel.setText("reviewId");
        roundedPanel1.add(reviewIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        reviewCommentLabel.setText("reviewComment");
        roundedPanel1.add(reviewCommentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 422, -1));

        datatimeLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        datatimeLabel.setText("dateTime");
        roundedPanel1.add(datatimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 10, 262, -1));

        ratingsLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        ratingsLabel.setText("ratings");
        roundedPanel1.add(ratingsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 16, 62, 58));

        ratingImage.setPreferredSize(new java.awt.Dimension(44, 43));
        roundedPanel1.add(ratingImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 25, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datatimeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ratingImage;
    private javax.swing.JLabel ratingsLabel;
    private javax.swing.JLabel reviewCommentLabel;
    private javax.swing.JLabel reviewIdLabel;
    private method.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
