/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.util.ArrayList;
import java.util.List;
import managefile.DeliveryReview;
import managefile.readFile;

/**
 *
 * @author Asus
 */
public class runnerPanel extends javax.swing.JPanel {
    private String runnerId;
    private String name;
    private String phoneNumber;
    private String email;
    DeliveryReview deliveryReview = new DeliveryReview();
    readFile read = new readFile();
    managerAccountManager acc = new managerAccountManager();
    /**
     * Creates new form deliveryPanel
     */
    public runnerPanel(String runnerId, String name, String phoneNumber, String email) {
        this.runnerId = runnerId;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        initComponents();
        this.setSize(300,190);
        runnerNameLabel.setText(name);
        runnerPhoneLabel.setText(phoneNumber);
        runnerEmailLabel.setText(email);
        List<DeliveryReview> reviews = read.readDeliveryReview(deliveryReview.getFilepath());
        List<String> ratings = new ArrayList();
        for (DeliveryReview review : reviews){
            if(review.getRunnerID().equals(runnerId)){
                ratings.add(review.getRating());
            }
        }
        double totalRatings = acc.calculateTotalRatings(ratings);
        ratingsLabel.setText("*" + Double.toString(totalRatings));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        vendorImagePanel = new javax.swing.JPanel();
        runnerDetailsPanel = new javax.swing.JPanel();
        runnerNameLabel = new javax.swing.JLabel();
        runnerEmailLabel = new javax.swing.JLabel();
        runnerPhoneLabel = new javax.swing.JLabel();
        ratingsLabel = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        vendorImagePanel.setBackground(java.awt.Color.black);
        vendorImagePanel.setPreferredSize(new java.awt.Dimension(280, 130));

        javax.swing.GroupLayout vendorImagePanelLayout = new javax.swing.GroupLayout(vendorImagePanel);
        vendorImagePanel.setLayout(vendorImagePanelLayout);
        vendorImagePanelLayout.setHorizontalGroup(
            vendorImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        vendorImagePanelLayout.setVerticalGroup(
            vendorImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        runnerNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        runnerNameLabel.setText("Runner Name");

        runnerEmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        runnerEmailLabel.setText("Runner Email");

        runnerPhoneLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        runnerPhoneLabel.setText("Phone Number");

        ratingsLabel.setText("Ratings");

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout runnerDetailsPanelLayout = new javax.swing.GroupLayout(runnerDetailsPanel);
        runnerDetailsPanel.setLayout(runnerDetailsPanelLayout);
        runnerDetailsPanelLayout.setHorizontalGroup(
            runnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runnerDetailsPanelLayout.createSequentialGroup()
                .addGroup(runnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(runnerDetailsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(runnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(runnerEmailLabel)
                            .addComponent(runnerPhoneLabel)))
                    .addGroup(runnerDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(runnerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(runnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, runnerDetailsPanelLayout.createSequentialGroup()
                        .addComponent(viewBtn)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, runnerDetailsPanelLayout.createSequentialGroup()
                        .addComponent(ratingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        runnerDetailsPanelLayout.setVerticalGroup(
            runnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runnerDetailsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(runnerNameLabel)
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(runnerEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(runnerPhoneLabel))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, runnerDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ratingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(runnerDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vendorImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(vendorImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(runnerDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(runnerId);
        runnerDetails runnerDetails = new runnerDetails(runnerId);
        runnerDetails.run();
       
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel ratingsLabel;
    private javax.swing.JPanel runnerDetailsPanel;
    private javax.swing.JLabel runnerEmailLabel;
    private javax.swing.JLabel runnerNameLabel;
    private javax.swing.JLabel runnerPhoneLabel;
    private javax.swing.JPanel vendorImagePanel;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
