/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manager;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import managefile.Data;
import managefile.DeliveryReview;
import managefile.Runner;

/**
 *
 * @author Asus
 */
public class runnerDetails extends javax.swing.JFrame {
    private String runnerId;
    private String runnerName;
    private String runnerEmail;
    private String runnerPhone;
    private String runnerStatus;
    private double totalRatings;
    Runner runner = new Runner();
    managerAccountManager backend = new managerAccountManager();
    Data data = new Data();
    DeliveryReview review = new DeliveryReview();
    private String reviewFilepath = review.getFilepath();
    String runnerFilepath = runner.getFilepath();
    
    /**
     * Creates new form runnerReviews
     */
    public runnerDetails(String runnerId, double totalRatings) {
        initComponents();
        this.runnerId = runnerId;
        this.totalRatings = totalRatings;
        this.setSize(600,650);
        String[][] runnerDetails = data.retrieveDataAsArray(0,runnerId,runnerFilepath);
        for (String[] runnerInfo : runnerDetails){
            this.runnerName = runnerInfo[1];
            this.runnerEmail = runnerInfo[2];
            this.runnerPhone = runnerInfo[3];
            this.runnerStatus = runnerInfo[5];
        }
        ratingLabel.setText(String.format("%.1f", totalRatings));
        runnerImage.setIcon(backend.scale.processImage("src\\main\\java\\image_repository\\man.png", 190, 155));
        ratingImage.setIcon(backend.scale.processImage("src\\main\\java\\image_repository\\star.png", 48, 50));
        System.out.println(runnerName);
        runnerNameLabel.setText(runnerName);
        runnerEmailLabel.setText(runnerEmail);
        runnerPhoneLabel.setText(runnerPhone);
        runnerStatusLabel.setText(runnerStatus);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
        showRunnerReviews();
    }
    
    public void showRunnerReviews(){
        reviewHistoryPanel.setLayout(new FlowLayout());
        JPanel containerPanel = new JPanel(new GridLayout(0, 1, 1, 1));
        
        String[][] reviewsHistory = data.retrieveDataAsArray(2,runnerId,reviewFilepath);
        System.out.println(Arrays.deepToString(reviewsHistory));
        for (String[] reviews : reviewsHistory){
            if(!reviews[3].equals("null")){
                ratingPanel panel = new ratingPanel(reviews);
                containerPanel.add(panel);
            }
        }
        JScrollPane scrollPane = new JScrollPane(containerPanel);
        scrollPane.setPreferredSize(new Dimension(600,340));
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.getVerticalScrollBar().setUnitIncrement(20);
        scrollPane.getHorizontalScrollBar().setUnitIncrement(20);
        scrollPane.setBorder(null);
        reviewHistoryPanel.add(scrollPane, BorderLayout.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runnerDetailsPanel = new javax.swing.JPanel();
        runnerDetails = new javax.swing.JPanel();
        runnerNameLabel = new javax.swing.JLabel();
        runnerEmailLabel = new javax.swing.JLabel();
        runnerPhoneLabel = new javax.swing.JLabel();
        runnerStatusLabel = new javax.swing.JLabel();
        runnerImage = new javax.swing.JLabel();
        reviewHistoryPanel = new javax.swing.JPanel();
        totalRatingsPanel = new javax.swing.JPanel();
        totalRatingsLabel = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ratingImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        runnerNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        runnerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        runnerNameLabel.setText("Runner Name");

        runnerEmailLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        runnerEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        runnerEmailLabel.setText("Runner Email");
        runnerEmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        runnerPhoneLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        runnerPhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        runnerPhoneLabel.setText("Runner Phone");
        runnerPhoneLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        runnerStatusLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        runnerStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        runnerStatusLabel.setText("Runner Status");
        runnerStatusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout runnerDetailsLayout = new javax.swing.GroupLayout(runnerDetails);
        runnerDetails.setLayout(runnerDetailsLayout);
        runnerDetailsLayout.setHorizontalGroup(
            runnerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(runnerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
            .addComponent(runnerEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(runnerDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(runnerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runnerPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(runnerStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        runnerDetailsLayout.setVerticalGroup(
            runnerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runnerDetailsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(runnerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runnerEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runnerPhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runnerStatusLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        runnerImage.setPreferredSize(new java.awt.Dimension(190, 155));

        javax.swing.GroupLayout runnerDetailsPanelLayout = new javax.swing.GroupLayout(runnerDetailsPanel);
        runnerDetailsPanel.setLayout(runnerDetailsPanelLayout);
        runnerDetailsPanelLayout.setHorizontalGroup(
            runnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runnerDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(runnerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runnerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        runnerDetailsPanelLayout.setVerticalGroup(
            runnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runnerDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(runnerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(runnerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(runnerImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        reviewHistoryPanel.setPreferredSize(new java.awt.Dimension(215, 215));

        javax.swing.GroupLayout reviewHistoryPanelLayout = new javax.swing.GroupLayout(reviewHistoryPanel);
        reviewHistoryPanel.setLayout(reviewHistoryPanelLayout);
        reviewHistoryPanelLayout.setHorizontalGroup(
            reviewHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        reviewHistoryPanelLayout.setVerticalGroup(
            reviewHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        totalRatingsLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        totalRatingsLabel.setText("Total Ratings:");

        ratingLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        ratingLabel.setText("4.5");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Reviews");

        javax.swing.GroupLayout totalRatingsPanelLayout = new javax.swing.GroupLayout(totalRatingsPanel);
        totalRatingsPanel.setLayout(totalRatingsPanelLayout);
        totalRatingsPanelLayout.setHorizontalGroup(
            totalRatingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalRatingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalRatingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(totalRatingsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totalRatingsPanelLayout.setVerticalGroup(
            totalRatingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalRatingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalRatingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalRatingsLabel)
                    .addComponent(ratingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratingImage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(runnerDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reviewHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addComponent(totalRatingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(runnerDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalRatingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(reviewHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void run() {
        new runnerDetails(runnerId, totalRatings).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ratingImage;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JPanel reviewHistoryPanel;
    private javax.swing.JPanel runnerDetails;
    private javax.swing.JPanel runnerDetailsPanel;
    private javax.swing.JLabel runnerEmailLabel;
    private javax.swing.JLabel runnerImage;
    private javax.swing.JLabel runnerNameLabel;
    private javax.swing.JLabel runnerPhoneLabel;
    private javax.swing.JLabel runnerStatusLabel;
    private javax.swing.JLabel totalRatingsLabel;
    private javax.swing.JPanel totalRatingsPanel;
    // End of variables declaration//GEN-END:variables
}
