/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.io.File;
import javax.swing.JOptionPane;
import managefile.Food;

/**
 *
 * @author Asus
 */
public class VendorFoodPanel extends javax.swing.JPanel {
    private String foodId;
    managerAccountManager acc = new managerAccountManager();
    Food food = new Food();
    private ManagerVendorItem parent;
    /**
     * Creates new form VendorFoodPanel
     */
    public VendorFoodPanel(String foodId, ManagerVendorItem parent) {
        initComponents();
        this.parent = parent;
        this.foodId = foodId;
        Food foodDetails = acc.getFoodDetails(foodId);
        foodNameLabel.setText(foodDetails.getName());
        descriptionLabel.setText(foodDetails.getDescription());
        priceLabel.setText(foodDetails.getPrice());
        File imageFile = new File(foodDetails.getImagepath());
        if (imageFile.exists()){
            foodImage.setIcon(acc.scale.processImage(foodDetails.getImagepath(), 82, 77));
        }else{
            foodImage.setIcon(acc.scale.processImage("src\\main\\java\\image_repository\\food-stall.png", 82, 77));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new method.RoundedPanel();
        descriptionLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        roundedButton1 = new method.RoundedButton();
        foodNameLabel = new javax.swing.JLabel();
        foodImage = new javax.swing.JLabel();

        roundedPanel1.setPreferredSize(new java.awt.Dimension(637, 120));

        descriptionLabel.setText("Description");

        priceLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        priceLabel.setText("Price");

        roundedButton1.setText("Delete");
        roundedButton1.setBorderColor(java.awt.Color.red);
        roundedButton1.setColorClick(new java.awt.Color(255, 102, 102));
        roundedButton1.setColorOver(new java.awt.Color(255, 51, 51));
        roundedButton1.setRadius(100);
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });

        foodNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        foodNameLabel.setText("Name");

        foodImage.setPreferredSize(new java.awt.Dimension(82, 77));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(foodNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceLabel))
                    .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        // TODO add your handling code here:
        acc.removeFood(foodId);
        parent.removeFoodPanel(this);
        JOptionPane.showMessageDialog(
            null, 
            "Food Removed Successfully!", 
            "Food Removed", 
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_roundedButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel foodImage;
    private javax.swing.JLabel foodNameLabel;
    private javax.swing.JLabel priceLabel;
    private method.RoundedButton roundedButton1;
    private method.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
