/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

/**
 *
 * @author Asus
 */
public class vendorPanel extends javax.swing.JPanel {
    private String vendorId;
    private String vendorName;
    private String vendorStallName;
    private String vendorStallType;
    /**
     * Creates new form vendorPanel
     */
    public vendorPanel(String vendorId, String vendorName, String vendorStallName, String vendorStallType) {
        this.vendorId = vendorId;
        this.vendorName = vendorName;
        this.vendorStallName = vendorStallName;
        this.vendorStallType = vendorStallType;
        initComponents();
        this.setSize(300,190);
        vendorStallNameLabel.setText(vendorStallName);
        vendorNameLabel.setText(vendorName);
        vendorTypeLabel.setText(vendorStallType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vendorImagePanel = new javax.swing.JPanel();
        vendorDetailsPanel = new javax.swing.JPanel();
        vendorStallNameLabel = new javax.swing.JLabel();
        vendorNameLabel = new javax.swing.JLabel();
        vendorTypeLabel = new javax.swing.JLabel();
        ratingsLabel = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.BorderLayout());

        vendorImagePanel.setBackground(java.awt.Color.black);
        vendorImagePanel.setPreferredSize(new java.awt.Dimension(280, 130));

        javax.swing.GroupLayout vendorImagePanelLayout = new javax.swing.GroupLayout(vendorImagePanel);
        vendorImagePanel.setLayout(vendorImagePanelLayout);
        vendorImagePanelLayout.setHorizontalGroup(
            vendorImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        vendorImagePanelLayout.setVerticalGroup(
            vendorImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        vendorStallNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        vendorStallNameLabel.setText("Vendor Stall Name");

        vendorNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendorNameLabel.setText("Vendor Name");

        vendorTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendorTypeLabel.setText("Vendor Type");

        ratingsLabel.setText("Ratings");

        viewBtn.setText("View");

        javax.swing.GroupLayout vendorDetailsPanelLayout = new javax.swing.GroupLayout(vendorDetailsPanel);
        vendorDetailsPanel.setLayout(vendorDetailsPanelLayout);
        vendorDetailsPanelLayout.setHorizontalGroup(
            vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addComponent(vendorStallNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ratingsLabel)
                        .addGap(14, 14, 14))
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendorTypeLabel)
                            .addComponent(vendorNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBtn)
                        .addGap(29, 29, 29))))
        );
        vendorDetailsPanelLayout.setVerticalGroup(
            vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(vendorStallNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ratingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vendorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(vendorTypeLabel))
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewBtn)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendorDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vendorImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(vendorImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(vendorDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ratingsLabel;
    private javax.swing.JPanel vendorDetailsPanel;
    private javax.swing.JPanel vendorImagePanel;
    private javax.swing.JLabel vendorNameLabel;
    private javax.swing.JLabel vendorStallNameLabel;
    private javax.swing.JLabel vendorTypeLabel;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
