/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manager;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import managefile.VendorReview;
import managefile.readFile;

/**
 *
 * @author Asus
 */
public class vendorPanel extends javax.swing.JPanel {
    private String vendorId;
    private String vendorName;
    private String vendorStallName;
    private String vendorStallType;
    private String vendorImagePath;
    private String type;
    VendorReview orderReview = new VendorReview();
    readFile read = new readFile();
    managerAccountManager acc = new managerAccountManager();
    
    /**
     * Creates new form vendorPanel
     */
    public vendorPanel(String type, String vendorId, String vendorName, String vendorStallName, String vendorStallType, String vendorImagePath) {
        this.vendorId = vendorId;
        this.vendorName = vendorName;
        this.vendorStallName = vendorStallName;
        this.vendorStallType = vendorStallType;
        this.vendorImagePath = vendorImagePath;
        this.type = type;
        initComponents();
        this.setSize(300,190);
        if (!vendorImagePath.equals("null")){
            vendorImage.setIcon(acc.scale.processImage(vendorImagePath, 311, 175));
        }else{
            vendorImage.setIcon(acc.scale.processImage("src\\main\\java\\image_repository\\food-stall.png", 311, 175));
        }
        vendorStallNameLabel.setText(vendorStallName);
        vendorNameLabel.setText(vendorName);
        vendorTypeLabel.setText(vendorStallType);
        List<VendorReview> reviews = read.readVendorReview(orderReview.getFilepath());

        List<String> ratings = new ArrayList();
        for (VendorReview review : reviews){
            if(review.getVendorID().equals(vendorId)){
                ratings.add(review.getRating());
            }
        }
        double totalRatings = acc.calculateTotalRatings(ratings);
        ratingsLabel.setText(String.format("%.1f", totalRatings));
        ratingImage.setIcon(acc.scale.processImage("src\\main\\java\\image_repository\\star.png", 33, 33));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vendorDetailsPanel = new javax.swing.JPanel();
        vendorStallNameLabel = new javax.swing.JLabel();
        vendorNameLabel = new javax.swing.JLabel();
        vendorTypeLabel = new javax.swing.JLabel();
        ratingsLabel = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        ratingImage = new javax.swing.JLabel();
        vendorImage = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.BorderLayout());

        vendorStallNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        vendorStallNameLabel.setText("Vendor Stall Name");

        vendorNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendorNameLabel.setText("Vendor Name");

        vendorTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendorTypeLabel.setText("Vendor Type");

        ratingsLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        ratingsLabel.setText("Ratings");

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        ratingImage.setPreferredSize(new java.awt.Dimension(33, 33));

        javax.swing.GroupLayout vendorDetailsPanelLayout = new javax.swing.GroupLayout(vendorDetailsPanel);
        vendorDetailsPanel.setLayout(vendorDetailsPanelLayout);
        vendorDetailsPanelLayout.setHorizontalGroup(
            vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addComponent(vendorStallNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ratingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ratingImage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addGroup(vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendorTypeLabel)
                            .addComponent(vendorNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBtn)
                        .addGap(29, 29, 29))))
        );
        vendorDetailsPanelLayout.setVerticalGroup(
            vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                .addGroup(vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(vendorStallNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ratingImage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendorDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ratingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(vendorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addComponent(vendorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vendorTypeLabel))
                    .addGroup(vendorDetailsPanelLayout.createSequentialGroup()
                        .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        vendorImage.setOpaque(true);
        vendorImage.setPreferredSize(new java.awt.Dimension(311, 175));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendorDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vendorImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(vendorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(vendorDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Vendor ID: " + vendorId);
        if(this.type.equals("Revenue")){
            vendorRevenue vendorPage = new vendorRevenue(vendorId);
            vendorPage.run();
        }else if (this.type.equals("Food")){
            ManagerVendorItem vendorItem = new ManagerVendorItem(vendorId);
            vendorItem.run();
        }
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ratingImage;
    private javax.swing.JLabel ratingsLabel;
    private javax.swing.JPanel vendorDetailsPanel;
    private javax.swing.JLabel vendorImage;
    private javax.swing.JLabel vendorNameLabel;
    private javax.swing.JLabel vendorStallNameLabel;
    private javax.swing.JLabel vendorTypeLabel;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
